# Flutter Linting Configuration
# This file configures the analyzer with Flutter's recommended linting rules
# along with additional custom rules for better code quality and consistency.

# Include Flutter's recommended lints and custom analysis configuration files
include:
  - package:flutter_lints/flutter.yaml
  - analysis_options/analysis_options_common.yaml
  - analysis_options/analysis_options_style.yaml
  - analysis_options/analysis_options_flutter.yaml
  - analysis_options/analysis_options_documentation.yaml
  - analysis_options/analysis_options_riverpod.yaml

# Analyzer plugins
analyzer:
  plugins:
    - custom_lint

dart_code_metrics:
  extends:
    - recommended

# Note: All analyzer and linter rules are now defined in their respective files in the analysis_options/ directory.
