# Build configuration for optimized code generation
# This file configures build_runner for Riverpod, Freezed, and JSON serialization

targets:
  # Default target for all builders
  $default:
    # Global build settings
    builders:
      # Riverpod code generation
      riverpod_generator|riverpod_generator:
        enabled: true
        generate_for:
          - lib/**
          - test/**
        options:
          # Generate providers with optimized imports
          generate_riverpod_debug_name: true
          # Enable scoped providers for better performance
          generate_scoped_providers: true
          # Custom output configuration
          build_extensions:
             ".dart": [".g.dart"]
          # Performance optimizations
          runs_before: ["json_serializable|json_serializable"]
          applies_builders: ["source_gen|combining_builder"]

      # Freezed code generation
      freezed|freezed:
        enabled: true
        generate_for:
          - lib/**
          - test/**
        options:
          # Enable all Freezed features
          generate_copyWith: true
          generate_equal: true
          generate_toString: true
          generate_toJson: true
          generate_fromJson: true
          # Use new pattern matching syntax
          use_pattern_matching: true
          # Generate sealed classes for better performance
          generate_sealed_classes: true
          # Custom output configuration
          build_extensions:
            ".dart": [".freezed.dart"]
          # Dependency tracking
          runs_before: ["json_serializable|json_serializable"]

      # JSON serialization
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          - lib/**
          - test/**
        options:
          # Performance optimizations
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
          create_field_map: false
          create_per_field_to_json: false

      # Go Router code generation
      go_router_builder|go_router_builder:
        enabled: true
        generate_for:
          - lib/router/**.dart
          - lib/screens/**.dart
        options:
          # Generate type-safe routes with enhanced features
          generate_go_route_information: true
          # Enable debug logging for route generation
          debug_logging: true
          # Generate route helper methods
          generate_route_helper: true
          # Generate route names as constants
          generate_route_names: true
          # Custom output configuration
          build_extensions:
            ".dart": [".g.dart"]
          # Ensure proper dependency ordering
          runs_after:
            - "freezed|freezed"
            - "json_serializable|json_serializable"
          applies_builders:
            - "source_gen|combining_builder"