name: Flutter CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up FVM & Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --no-fatal-infos
      - name: Test
        run: flutter test --coverage
      - name: Build web (smoke)
        run: flutter build web --release --base-href "/" --pwa-strategy offline-first
        if: github.event_name == 'push'
