name: Flutter CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up FVM & Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true
      - name: Create env file from secrets
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> supabase_config.env
          echo "SUPABASE_ANON_KEY=$SUPABASE_KEY" >> supabase_config.env
          echo "SENTRY_DSN=$SENTRY_DSN" >> supabase_config.env
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --no-fatal-infos
      - name: Test
        run: flutter test --coverage
      - name: Build web (smoke)
        run: flutter build web --release --base-href "/" --pwa-strategy offline-first
        if: github.event_name == 'push'
